core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm.urls'))
]

core/crm/urls.py
from django.urls import path
from .views import IndexView

app_name = 'crm'


urlpatterns = [
    path('', IndexView.as_view(), name='index')
]

core/crm/models.py
from django.db import models

# Create your models here.

core/crm/views.py
from django.views.generic import TemplateView


# Create your views here.

class IndexView(TemplateView):
    template_name = "crm/index.html"

core/templates/crm/index.html
{% extends "layouts/base.html" %}

    {% block content %}
<div class="container col-xxl-8 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
      <div class="col-10 col-sm-8 col-lg-6">
        <img src="bootstrap-themes.png" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
      </div>
      <div class="col-lg-6">
        <h1 class="display-5 fw-bold lh-1 mb-3">CRM built with Django</h1>
        <p class="lead">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start">
          <button type="button" class="btn btn-primary btn-lg px-4 me-md-2">Primary</button>
          <button type="button" class="btn btn-outline-secondary btn-lg px-4">Default</button>
        </div>
      </div>
    </div>
  </div>

          {% if request.user.is_authenticated %}
<div class="container justify-content-center">Hi user, {{user.email}}</div>
{% else %}

<div class="container justify-content-center">Is not authenticated</div>
{% endif %}
    {% endblock content %}

core/templates/layouts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
        <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>CRM project 0.0.1</title>

        <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
      <div >
        {% include 'layouts/navbar.html' %}
      </div>

    <div>
      {% block content %}

      {% endblock content %}
    </div>
    <!-- Scripts JS File -->
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>

    <!-- Bootstrap Bundle  -->
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
  </body>
</html>

core/templates/layouts/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'crm:index' %}">
      <img src="{% static '/img/logo.png' %}" alt="Logo" width="35" height="35" class="d-inline-block align-text-top">
      -CRM
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 nav col-12 col-md-auto mb-2 justify-content-center mb-md-0 ">
        <li class="nav-item">
          <a class="nav-link" href="#">Функциональность</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Доступности</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">О Нас</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown link
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <div class="d-flex align-items-center">
        <div class="flex-shrink-0 dropdown me-3">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Язык
          </a>
          <ul class="dropdown-menu text-small shadow">
            <li><a class="dropdown-item" href="#">New project...</a></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
          </ul>
        </div>
        <div class="nav">
             {% if request.user.is_authenticated %}
          <a type="button" class="btn btn-outline-primary me-2" href="">Logout</a>
          {% else %}
          <a type="button" class="btn btn-outline-primary me-2" href="">Login</a>
          <a type="button" class="btn btn-outline-primary" href="">Register</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</nav></title>
</head>
<body>

</body>
</html>